# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(default='TestCase', max_length=200),
        ),
    ]
