# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0002_case_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='case',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
