# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0003_auto_20161026_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('label', models.CharField(max_length=100)),
                ('major_number', models.CharField(max_length=10)),
                ('minor_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('deployed', 'Deployed')], default='scheduled', max_length=30)),
            ],
        ),
    ]
