# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0005_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testlibrary.Case')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
