# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0006_auto_20161027_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='case_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testlibrary.CaseHistory'),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='revision_number',
            field=models.IntegerField(default=1),
        ),
    ]
