# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0008_auto_20161027_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, null=True)),
                ('case_type', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='external_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='external_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='external_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='external_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
