# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0010_case_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(default='New Data Field', max_length=200)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean')], default='string', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(default='New Data Set', max_length=200)),
                ('data_fields', models.ManyToManyField(to='testlibrary.DataField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='data_sets',
            field=models.ManyToManyField(to='testlibrary.DataSet'),
        ),
    ]
