# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0011_auto_20161121_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('result', models.CharField(choices=[('scheduled', 'Scheduled'), ('pass', 'Pass'), ('fail', 'Fail'), ('blocked', 'Blocked'), ('warn', 'Warn'), ('skipped', 'Skipped'), ('paused', 'Paused')], default='Scheduled', max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testlibrary.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='Created', max_length=50)),
                ('test_cases', models.ManyToManyField(to='testlibrary.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
