# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0013_auto_20161122_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
