# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0014_auto_20161122_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='test_cases',
            field=models.ManyToManyField(null=True, to='testlibrary.Case'),
        ),
    ]
