# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testlibrary', '0016_auto_20161122_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='test_results',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testlibrary.TestRun'),
        ),
    ]
